import { Card, CardContent } from "@/components/ui/card"
import { Separator } from "@/components/ui/separator"
import { Button } from "@/components/ui/button"
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs"
import { ChevronLeft } from "lucide-react"
import Link from "next/link"

export default function ApplicationsPage() {
  return (
    <div className="container py-10">
      <div className="max-w-4xl mx-auto space-y-8">
        <div className="flex items-center space-x-4">
          <Link href="/basics">
            <Button variant="ghost" size="sm">
              <ChevronLeft className="mr-2 h-4 w-4" /> Back to Modules
            </Button>
          </Link>
          <Separator orientation="vertical" className="h-6" />
          <div className="text-sm text-muted-foreground">Module 4 of 4</div>
        </div>

        <div className="space-y-2">
          <h1 className="text-4xl font-bold tracking-tight">Applications & Advanced Topics</h1>
          <p className="text-xl text-muted-foreground">
            Apply fluid mechanics principles to real-world problems
          </p>
        </div>

        <Tabs defaultValue="aerodynamics" className="space-y-6">
          <TabsList className="grid w-full grid-cols-2 md:grid-cols-6">
            <TabsTrigger value="aerodynamics">Aerodynamics</TabsTrigger>
            <TabsTrigger value="hydraulics">Hydraulics</TabsTrigger>
            <TabsTrigger value="open-channel">Open Channels</TabsTrigger>
            <TabsTrigger value="waves">Waves</TabsTrigger>
            <TabsTrigger value="cfd">CFD</TabsTrigger>
            <TabsTrigger value="measurement">Measurements</TabsTrigger>
          </TabsList>

          {/* Aerodynamics Tab */}
          <TabsContent value="aerodynamics" className="space-y-6">
            <Card>
              <CardContent className="p-6 space-y-6">
                <h2 className="text-2xl font-semibold tracking-tight">Aerodynamics and Lift Generation</h2>

                <div className="prose prose-lg dark:prose-invert max-w-none">
                  <p>
                    <strong>Aerodynamics</strong> is the study of how air flows around solid objects, with particular
                    focus on the forces generated by this interaction. It is a specialized branch of fluid dynamics
                    that has far-reaching applications in aviation, automotive design, wind energy, and sports.
                  </p>

                  <h3 className="text-xl font-semibold mt-6">Lift Generation</h3>

                  <p>
                    One of the most important concepts in aerodynamics is <strong>lift</strong> - the force that acts
                    perpendicular to the direction of flow when a fluid flows past an object. Lift is what allows aircraft
                    to fly, and it results from several mechanisms:
                  </p>

                  <ul>
                    <li>
                      <strong>Pressure difference</strong> - Airfoil shapes create lower pressure on top and higher
                      pressure on the bottom, resulting in an upward force
                    </li>
                    <li>
                      <strong>Newton's laws</strong> - Air is deflected downward by the wing, resulting in an equal
                      and opposite reaction force upward
                    </li>
                    <li>
                      <strong>Circulation theory</strong> - Mathematically, lift can be explained by circulation of air
                      around the airfoil
                    </li>
                  </ul>

                  <h3 className="text-xl font-semibold mt-6">Drag</h3>

                  <p>
                    <strong>Drag</strong> is the force that opposes motion through a fluid, acting parallel to the direction of flow.
                    It consists of:
                  </p>

                  <ul>
                    <li><strong>Form drag</strong> - Caused by pressure differences between front and back of an object</li>
                    <li><strong>Skin friction drag</strong> - Caused by viscous forces at the fluid-solid interface</li>
                    <li><strong>Induced drag</strong> - A byproduct of lift generation in finite wings (wingtip vortices)</li>
                    <li><strong>Wave drag</strong> - Occurs in transonic and supersonic flows due to shock wave formation</li>
                  </ul>

                  <h3 className="text-xl font-semibold mt-6">Applications of Aerodynamics</h3>

                  <ul>
                    <li>
                      <strong>Aircraft design</strong> - Optimizing wing shapes, control surfaces, and overall aircraft configuration
                      to maximize lift and minimize drag
                    </li>
                    <li>
                      <strong>Automotive engineering</strong> - Reducing drag to improve fuel efficiency and enhancing downforce
                      for better handling in high-performance vehicles
                    </li>
                    <li>
                      <strong>Wind turbines</strong> - Designing blades to efficiently extract energy from the wind
                    </li>
                    <li>
                      <strong>Structural engineering</strong> - Analyzing wind loads on buildings, bridges, and other structures
                    </li>
                    <li>
                      <strong>Sports equipment</strong> - Optimizing the aerodynamics of balls, bicycles, and athletic apparel
                    </li>
                  </ul>
                </div>

                <div className="bg-muted rounded-md p-4 mt-6">
                  <h3 className="font-medium mb-2">Key Concepts</h3>
                  <ul className="space-y-1 text-sm">
                    <li className="flex items-start">
                      <div className="w-1.5 h-1.5 rounded-full bg-primary mt-1.5 mr-2 flex-shrink-0"></div>
                      <span>Lift is generated due to pressure differences created by an airfoil shape</span>
                    </li>
                    <li className="flex items-start">
                      <div className="w-1.5 h-1.5 rounded-full bg-primary mt-1.5 mr-2 flex-shrink-0"></div>
                      <span>Drag reduction is a primary goal in many aerodynamic designs</span>
                    </li>
                    <li className="flex items-start">
                      <div className="w-1.5 h-1.5 rounded-full bg-primary mt-1.5 mr-2 flex-shrink-0"></div>
                      <span>Bernoulli's principle plays a key role in explaining basic lift generation</span>
                    </li>
                  </ul>
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          {/* Hydraulics Tab */}
          <TabsContent value="hydraulics" className="space-y-6">
            <Card>
              <CardContent className="p-6">
                <h2 className="text-2xl font-semibold tracking-tight">Hydraulic Systems and Machinery</h2>

                <div className="prose prose-lg dark:prose-invert max-w-none">
                  <p>
                    <strong>Hydraulics</strong> is the branch of fluid mechanics that deals with the practical applications
                    of fluid properties, particularly liquids under pressure. Hydraulic systems use pressurized fluid to
                    transmit force and motion, offering significant advantages in power transmission.
                  </p>

                  <h3 className="text-xl font-semibold mt-6">Principles of Hydraulic Systems</h3>

                  <ul>
                    <li>
                      <strong>Pascal's law</strong> - Pressure applied to an enclosed fluid is transmitted equally in all directions,
                      forming the foundation of hydraulic systems
                    </li>
                    <li>
                      <strong>Force multiplication</strong> - A small force applied to a small piston can create a large force on a
                      large piston (F₁/A₁ = F₂/A₂)
                    </li>
                    <li>
                      <strong>Incompressibility</strong> - Liquids are nearly incompressible, allowing efficient power transmission
                    </li>
                    <li>
                      <strong>Fluid friction</strong> - Energy losses occur due to friction within the fluid and at boundaries
                    </li>
                  </ul>

                  <h3 className="text-xl font-semibold mt-6">Common Hydraulic Components</h3>

                  <ul>
                    <li><strong>Pumps</strong> - Convert mechanical energy to hydraulic energy</li>
                    <li><strong>Actuators</strong> - Convert hydraulic energy back to mechanical energy (cylinders, motors)</li>
                    <li><strong>Valves</strong> - Control flow direction, pressure, and flow rate</li>
                    <li><strong>Accumulators</strong> - Store hydraulic energy for later use</li>
                    <li><strong>Filters</strong> - Remove contaminants from the hydraulic fluid</li>
                    <li><strong>Reservoirs</strong> - Store hydraulic fluid and allow for thermal expansion</li>
                  </ul>

                  <p>
                    Hydraulic systems are widely used for their ability to multiply force, provide precise control,
                    and deliver high power-to-weight ratios.
                  </p>
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          {/* Placeholder for other tabs */}
          <TabsContent value="open-channel">
            <Card>
              <CardContent className="p-6">
                <h2 className="text-2xl font-semibold tracking-tight">Open Channel Flow</h2>
                <div className="prose prose-lg dark:prose-invert max-w-none">
                  <p>Content for open channel flow will be added here...</p>
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="waves">
            <Card>
              <CardContent className="p-6">
                <h2 className="text-2xl font-semibold tracking-tight">Waves and Wave Dynamics</h2>
                <div className="prose prose-lg dark:prose-invert max-w-none">
                  <p>Content for waves and wave dynamics will be added here...</p>
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="cfd">
            <Card>
              <CardContent className="p-6">
                <h2 className="text-2xl font-semibold tracking-tight">Computational Fluid Dynamics</h2>
                <div className="prose prose-lg dark:prose-invert max-w-none">
                  <p>Content for computational fluid dynamics will be added here...</p>
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="measurement">
            <Card>
              <CardContent className="p-6">
                <h2 className="text-2xl font-semibold tracking-tight">Flow Measurement Techniques</h2>
                <div className="prose prose-lg dark:prose-invert max-w-none">
                  <p>Content for flow measurement techniques will be added here...</p>
                </div>
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>

        <div className="flex justify-between mt-10">
          <Link href="/basics/fluid-dynamics">
            <Button variant="outline">
              <ChevronLeft className="mr-2 h-4 w-4" /> Previous Module
            </Button>
          </Link>

          <Link href="/tests/quick-check">
            <Button>
              Take Knowledge Test
            </Button>
          </Link>
        </div>
      </div>
    </div>
  )
}
